# Default config file to generate ohm_maps
# This will run
#   - ohm_mapping framwork with a set of parameters
#   - ohm_offline_colourisation
#   -

# The @p raw_data_dirs are the absolute paths to the raw data directories
raw_data_dirs:
  -
# output of the data directory
out_data_dir: /data/data_set_out
ohm_resolutions: 

ohm_maps:
  max_ray_lentgh: 20 
  mapping_mode: "TM"     # 0: Occ, 1: NDT, 2: TM
  traj_type: "global"        # 0: odom, 1: global
  enable_traversal: true
  enable_second_returns: true
  
  ndt_options:
    ndt-cov-point-threshold:
    ndt-cov-prob-threshold:

ohm_offline_colourisation:
  enable_offline_colourisation: true

